---
- hosts: all
  become: yes
  become_method: sudo
  tasks:


    - name: Install required system packages
      apt: 
         name: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools'] 
         state: present
         update_cache: true

    - name: add docker gpg apt key
      apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present

    - name: add docker repository
      apt_repository:
         repo: deb https://download.docker.com/linux/ubuntu focal stable
         state: present

    - name: update apt and install docker-ce
      apt:
         name: docker-ce
         state: latest
         update_cache: true

    - name: install docker module for python
      pip:
         name: docker

    - name: install docker-compose
      get_url:
          url: https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-linux-x86_64
          dest: /usr/bin/docker-compose
          mode: 'u+x,g+x'
          force: yes

    - name: start up docker-compose
      shell: "chmod +x /usr/bin/docker-compose"

    - name: mkdir prometheus
      file:
          path=/opt/prometheus_stack/prometheus
          state=directory

    - name: copy prometheus.yml
      copy:
        src: ./prometheus.yml
        dest: /opt/prometheus_stack/prometheus
        remote_src: no
        mode: 0644
        owner: root
        group: root

    - name: copy docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /opt/prometheus_stack/
        remote_src: no
        mode: 0644
        owner: root
        group: root

    - name: docker-compose up -d
      shell: "cd /opt/prometheus_stack/ && docker-compose up -d"

    - name: copy grafana settings
      copy:
        src: ./grafana.db
        dest: /opt/prometheus_stack/grafana
        remote_src: no
        mode: 0644
        owner: root
        group: root

    - name: docker-compose restart
      shell: "cd /opt/prometheus_stack/ && docker-compose stop && docker-compose up -d"
